version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - "brainbicycle"
      - "pvinis"
    reviewers:
      - "artsy/mobile-platform"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - "brainbicycle"
      - "pvinis"
    reviewers:
      - "artsy/mobile-platform"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit to 0 to enable only security updates:
    open-pull-requests-limit: 0
    assignees:
      - "brainbicycle"
      - "pvinis"
    reviewers:
      - "artsy/mobile-platform"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    assignees:
     - brainbicycle
     - pvinis
    reviewers:
     - artsy/mobile-platform
