# CircleCI doesn't automatically run builds on the app_store_submission branch (only main and PRs)
# so this is a github action to force it to do so.
name: ZZ-Cross-CI Trigger promotion to app store

on:
  push:
    branches: [app_store_submission]

permissions:
  contents: read

jobs:
  trigger:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Trigger promotion
        run: |
          curl \
            -X POST \
            --header "Content-Type: application/json" \
            -d '{"branch": "app_store_submission"}' \
            https://circleci.com/api/v1.1/project/github/artsy/eigen/build?circle-token=${{ secrets.CircleToken }}
