name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  similarity-analysis:
    permissions:
      issues: write  # for actions-cool/issues-similarity-analysis to create issue comments
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          filter-threshold: 0.5
          title-excludes: ''
          comment-title: '### You may look for issues:'
          comment-body: '${index}. ${similarity} #${number}'
