# Upload 📷 UI snapshots to argos server, help visual regression testing.
name: 📷 UI Upload

on:
  workflow_run:
    workflows: ["📷 UI"]
    types:
      - completed

permissions:
  contents: read

jobs:
  upload-ui:
    permissions:
      actions: read  # for dawidd6/action-download-artifact to query and download artifacts
      pull-requests: read  # for dawidd6/action-download-artifact to query commit hash
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Download commit artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: commit

      - name: Save commit id
        id: commit
        run: echo "::set-output name=id::$(<commit.txt)"

      - name: Download branch artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: branch

      - name: Save branch id
        id: branch
        run: echo "::set-output name=id::$(<branch.txt)"

      - name: Download snapshots artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: snapshots
          path: imageSnapshots

      - name: Install
        run: npm i fast-glob lodash argos-cli

      - name: Upload argos-ci
        id: deploy
        run: npm run argos
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          ARGOS_GITHUB_BRANCH: ${{ steps.branch.outputs.id }}
          ARGOS_GITHUB_COMMIT: ${{ steps.commit.outputs.id }}
