version: 2.1

orbs:
  node: circleci/node@5.0.2
  queue: eddiewebb/queue@1.7.0
  horizon: artsy/release@0.0.1

commands:
  await-previous-builds:
    parameters:
      branch:
        description: The branch to wait on
        type: string
    steps:
      - queue/until_front_of_line:
          time: "30" # how long a queue will wait until the job exits
          only-on-branch: <<parameters.branch>> # restrict queueing to a specific branch (default *)
  install-node:
    steps:
      - run:
          name: Install Node 14 (Required for Yarn)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
            echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $BASH_ENV
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v14.17.1' >> $BASH_ENV
            echo 'nvm alias default v14.17.1' >> $BASH_ENV
            sudo mkdir ~/.config
            sudo chown -R $USER:$GROUP ~/.config
  generate-checksums:
    steps:
      - run:
          name: "Generate initial checksum manifests"
          command: |
            mkdir .manifests
            scripts/generate-manifest.js .manifests/node_modules '^yarn\.lock$' '^patches/' '^package\.json$'
            scripts/generate-manifest.js .manifests/js_transform '^\.manifests/node_modules' '^babel\.config\.js' '^relay\.config\.js' '^jest\.config\.js'
            scripts/generate-manifest.js .manifests/js_bundle '^\.manifests/js_transform' '^data/' '^index\.ios\.js' '^src/(?!.*(__mocks__|__fixtures__))'
            ls -lR emission > .manifests/emission_pod_file_list
            scripts/generate-manifest.js .manifests/cocoapods '^Podfile' '^Gemfile' '^\.manifests/emission_pod_file_list'
            scripts/generate-manifest.js .manifests/native_code '^\.manifests/node_modules' '^Podfile' '^Gemfile' '^emission/' '^Artsy' '^patches/react-native' '^\.env\.example'
            scripts/generate-manifest.js .manifests/android_native '^\.manifests/node_modules' '^android/' '^patches/react-native' '^\.env\.example'
  setup-env-file:
    steps:
      - run:
          name: "Set up .env file"
          command: touch .env.shared && scripts/setup-env-for-ci
  setup-awscli:
    steps:
      - run:
          name: "Set up aws cli not installed"
          command: scripts/setup-awscli
  install-node-modules:
    steps:
      - restore_cache:
          keys:
            - v6-node_modules-{{ checksum ".manifests/node_modules" }}-{{ arch }}
      - run:
          name: Install node modules
          command: ls node_modules || yarn install
      - save_cache:
          key: v6-node_modules-{{ checksum ".manifests/node_modules" }}-{{ arch }}
          paths:
            - node_modules
  run-relay-compiler:
    steps:
      - run:
          name: Run Relay compiler
          command: yarn relay
  update-echo:
    steps:
      - run:
          name: Update echo
          command: ./scripts/update-echo
  generate-query-map:
    steps:
      - run:
          name: Compile query map
          command: yarn relay
  test-js:
    steps:
      - restore_cache:
          keys:
            - v6-jest-{{ .Branch }}
      - run:
          name: Run TypeScript check
          command: yarn type-check
      - run:
          name: Run TSLint check
          command: yarn lint
      - run:
          name: Run jest tests
          command: yarn jest --ci --forceExit --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - save_cache:
          key: v6-jest-{{ .Branch }}
          paths:
            - .jest
  bundle-js:
    steps:
      - restore_cache:
          keys:
            - v6-js_bundle-{{ checksum ".manifests/js_bundle" }}
      - restore_cache:
          keys:
            - v6-metro-{{ checksum ".manifests/js_transform" }}
      - run:
          name: Bundle emission
          command: ls emission/Pod/Assets/Emission.js || yarn bundle-for-native-ci:ios
      - save_cache:
          key: v6-metro-{{ checksum ".manifests/js_transform" }}
          paths:
            - .metro
      - save_cache:
          key: v6-js_bundle-{{ checksum ".manifests/js_bundle" }}
          paths:
            - emission/Pod/Assets/Emission.js
            - emission/Pod/Assets/Emission.js.map
            - emission/Pod/Assets/assets
  install-gems:
    steps:
      - restore_cache:
          keys:
            - v4-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: v4-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - .vendor
  install-cocoapods:
    steps:
      - restore_cache:
          keys:
            - v9-pods-{{ checksum ".manifests/cocoapods" }}
      - run:
          name: Install Pods
          command: cd ios; bundle exec pod check --ignore-dev-pods || bundle exec pod install; cd ..;
      - save_cache:
          key: v9-pods-{{ checksum ".manifests/cocoapods" }}
          paths:
            - ios/Pods
            # this changes after pod install because we don't install dev tools on CI
            # so we save it to the cache to avoid comparison errors with Pods/Manifest.lock
            - ios/Podfile.lock
  build-app-ios:
    steps:
      - restore_cache:
          keys:
            - v6-app_build_ios-{{ checksum ".manifests/app_build" }}
      - run:
          name: Build App
          command: ./scripts/ci-ios
      - save_cache:
          key: v6-app_build_ios-{{ checksum ".manifests/app_build" }}
          paths:
            - derived_data
            - node_modules/react-native-config
  prep-android-env:
    steps:
      - attach_workspace:
          at: ../workspace
      - run:
          name: Clear project dir
          command: |
            rm -rf /Users/distiller/project
      - checkout
      - attach_workspace:
          at: .
      - install-node
      - setup-awscli
      - setup-env-file
      - restore_cache:
          keys:
            - v6-test-success-{{ checksum "../workspace/.manifests/android_native" }}
      - run:
          name: Quit early if possible
          command: |
            if test $CIRCLE_BRANCH != beta-android && ls build-success.log
            then
              circleci step halt
            fi
      - install-node-modules
      - run-relay-compiler
      - update-echo
      - install-gems
  build-app-android:
    steps:
      - restore_cache:
          keys:
            - v1-app_build_android-{{ checksum ".manifests/app_build" }}
      - generate-query-map
      - run:
          name: Download fonts from s3
          command: ./scripts/download-assets
      - run:
          name: Build App
          command: ./scripts/ci-android
      - save_cache:
          key: v1-app_build_android-{{ checksum ".manifests/app_build" }}
          paths:
            - android/build
            - android/app/build
            - node_modules/react-native-config

jobs:
  detect-secrets:
    docker:
      - image: lirantal/detect-secrets
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: ./scripts/secrets-check-all

  deploy-nightly-beta:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching

    macos:
      xcode: 13.2.1

    steps:
      - checkout
      - install-node
      - run:
          name: Deploy beta
          command: ./scripts/deploy-both

  update-metaphysics:
    executor:
      name: node/default
      tag: "14.17.1"
    steps:
      - checkout
      - generate-checksums
      - install-node-modules
      - run-relay-compiler
      - generate-query-map
      - run:
          name: Update metaphysics
          command: yarn update-metaphysics

  check-pr:
    executor:
      name: node/default
      tag: "14.17.1"
    steps:
      - checkout
      - generate-checksums
      - install-node-modules
      - run-relay-compiler
      - run:
          name: Danger
          command: yarn danger ci --verbose
      - run:
          name: Prevent Strictness Regressions
          command: node scripts/strictness-migration.js check-pr

  check-flags:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching

    macos:
      xcode: 13.2.1

    steps:
      - checkout
      - generate-checksums
      - install-node
      - install-gems
      - run:
          name: Check flags
          command: ./scripts/biweekly-flag-check.sh

  check-if-app-has-been-approved-for-release:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching

    macos:
      xcode: 13.2.1

    steps:
      - checkout
      - generate-checksums
      - install-gems
      - run:
          name: Check flags
          command: ./scripts/check-if-app-has-been-approved-for-release.sh

  check-metaphysics-freshness:
    executor:
      name: node/default
      tag: "14.17.1"
    steps:
      - checkout
      - run:
          name: apt-get update
          command: sudo apt-get update --fix-missing
      - run:
          name: Install Headless Chrome dependencies for puppeteer
          # from https://github.com/threetreeslight/puppeteer-orb/blob/master/orb.yml
          command: |
            sudo apt-get install --fix-missing -yq \
            gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - generate-checksums
      - install-node-modules
      - run-relay-compiler
      - run:
          name: Generate queries json
          command: yarn relay
      - run:
          name: Check Metaphysics freshness
          command: yarn ts-node ./metaphysics-queries-freshness-tests/test-freshness.ts

  build-test-js:
    executor:
      name: node/default
      tag: "14.17.1"
    resource_class: large
    steps:
      - checkout
      - generate-checksums
      - setup-awscli
      - setup-env-file
      - install-node-modules
      - run-relay-compiler
      - update-echo
      - generate-query-map
      - run:
          name: Check generated folder
          command: |
            if test "$(git diff -- src/__generated__)"
            then
              echo 'You forgot to run `yarn relay` before comitting'
              exit 1
            fi
      - test-js
      - bundle-js
      - run:
          name: Generate app_build manifest
          command: ./scripts/generate-manifest.js .manifests/app_build '^\./manifests/native_code' '^emission/Pod/Assets/'
      - store_artifacts:
          path: .manifests
      - store_test_results:
          path: ./reports/junit/
      - persist_to_workspace:
          root: .
          paths:
            - .manifests
            - emission/Pod/Assets

  build-test-app-ios:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching

    macos:
      xcode: 13.2.1

    steps:
      - attach_workspace:
          at: ../workspace
      - restore_cache:
          keys:
            - v7-test-success-{{ checksum "../workspace/.manifests/native_code" }}
      # we can quit the macos build early if there were no native code changes
      # and we're not on the beta branch
      - run:
          name: Quit early if possible
          command: |
            if test $CIRCLE_BRANCH != beta-ios && ls xcode_test_raw.log
            then
              circleci step halt
            fi
      - run:
          name: Quit early if Draft PR
          command: |
            if $(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/artsy/eigen/pulls/${CIRCLE_PULL_REQUEST##*/} | jq ".draft")
            then
              circleci step halt
            fi
      - run:
          name: Clear project dir
          command: |
            rm -rf /Users/distiller/project
      - checkout
      - attach_workspace:
          at: .
      - install-node
      - setup-awscli
      - setup-env-file
      - install-node-modules
      - run-relay-compiler
      - update-echo
      - install-gems
      - install-cocoapods
      - build-app-ios
      - run:
          name: Run tests if native code has changed
          command: ls xcode_test_raw.log || ./scripts/ci-test-ios
      - save_cache:
          key: v7-test-success-{{ checksum ".manifests/native_code" }}
          paths:
            - xcode_test_raw.log

      - store_artifacts:
          path: xcode_build_raw.log
          prefix: build

      - store_artifacts:
          path: xcode_test_raw.log
          prefix: tests

      - run:
          name: Danger
          command: bundle exec danger --danger_id=circle --dangerfile=Dangerfile.circle.rb --verbose

      - await-previous-builds:
          branch: beta-ios
      - run:
          name: Deploy if beta
          no_output_timeout: 20m
          command: ./scripts/deploy-if-beta-branch-ios

  build-test-app-android:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching
    docker:
      - image: circleci/android:api-29-node
    resource_class: large
    steps:
      - prep-android-env
      - await-previous-builds:
          branch: beta-android
      - build-app-android
      - run:
          name: Save success file
          command: echo yes > 'build-success.log'

      - store_artifacts:
          path: android/app/build/reports
          prefix: android-build

      - save_cache:
          key: v6-test-success-{{ checksum "../workspace/.manifests/android_native" }}
          paths:
            - build-success.log
      - run:
          name: Deploy if beta - play store and firebase
          command: ./scripts/deploy-if-beta-branch-android BOTH

  promote-beta-to-app-store:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - install-gems
      - await-previous-builds:
          branch: app_store_submission
      - run:
          name: Promote if app_store_submission
          command: ./scripts/promote-if-appstore-submission-branch

  promote-beta-to-play-store:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching

    docker:
      - image: circleci/android:api-29-node

    steps:
      - checkout
      - install-gems
      - await-previous-builds:
          branch: play_store_submission
      - run:
          name: Setup
          command: ./scripts/setup-distribute
      - run:
          name: Promote if play_store_submission
          command: ./scripts/promote-if-playstore-submission-branch

  update-changelog:
    executor:
      name: node/default
      tag: "14.17.1"

    steps:
      - checkout
      - generate-checksums
      - install-node-modules
      - run:
          name: Update Changelog
          command: node scripts/changelog/commitChangelog.js
      - store_artifacts:
          path: .manifests
  release-ios-app:
    environment:
      BUNDLE_PATH: .vendor # path to install gems and use for caching
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - install-gems
      - run:
          name: Release app version
          command: ./scripts/release-ios-app-branch
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - deploy-nightly-beta

  flag-check:
    triggers:
      - schedule:
          cron: "0 6 * * 4"
          filters:
            branches:
              only:
                - main
    jobs:
      - check-flags

  check-if-app-has-been-approved-for-release-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - check-if-app-has-been-approved-for-release

  update-changelog-workflow:
    jobs:
      - update-changelog:
          filters:
            branches:
              only:
                - main
  release-ios-app-workflow:
    jobs:
      - release-ios-app:
          filters:
            branches:
              only:
                - release-ios-app
  promote:
    jobs:
      - promote-beta-to-app-store:
          filters:
            branches:
              only:
                - app_store_submission
      - promote-beta-to-play-store:
          filters:
            branches:
              only:
                - play_store_submission

  test-build-deploy:
    jobs:
      - detect-secrets:
          filters:
            branches:
              ignore:
                - main
                - release
                - staging
      - check-pr:
          filters:
            branches:
              ignore:
                - main
                - beta-ios
                - beta-android
                - app_store_submission
                - play_store_submission
                - update-changelog
      - build-test-js:
          filters:
            branches:
              ignore:
                - app_store_submission
                - play_store_submission
                - update-changelog
      - horizon/block:
          context: horizon
          project_id: 37
          filters:
            branches:
              only:
                - beta-ios
                - beta-android
      - build-test-app-ios:
          filters:
            branches:
              ignore:
                - app_store_submission
                - play_store_submission
                - beta-android
                - update-changelog
          requires:
            - build-test-js
            - horizon/block
      - build-test-app-android:
          filters:
            branches:
              ignore:
                - app_store_submission
                - play_store_submission
                - beta-ios
                - update-changelog
          requires:
            - build-test-js
            - horizon/block
      - update-metaphysics:
          filters:
            branches:
              only:
                - beta-ios
                - beta-android
              ignore:
                - update-changelog
          requires:
            - build-test-app-ios
            - build-test-app-android
