name: Publish Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Checkout and pull branch
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Docker meta for the app
        id: metaapp
        uses: docker/metadata-action@v3
        with:
          images: codelit/courselit-app

      - name: Docker meta for the proxy
        id: metaproxy
        uses: docker/metadata-action@v3
        with:
          images: codelit/courselit-proxy

      - name: Build and push app 
        id: docker_build_app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/app/Dockerfile
          push: true
          tags: ${{ steps.metaapp.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_app.outputs.digest }}

      - name: Build and push proxy
        id: docker_build_proxy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/proxy/Dockerfile
          push: true
          tags: ${{ steps.metaproxy.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_proxy.outputs.digest }}